### ISSUE TITLE
problem in connect to jppf

### ISSUE THREAD

**Issue by hamidasgarian** [rethab/jppf-docker#1]
is there any makefile to run jppf?

after build image with command:
docker build -t jppf  .
docker run -dt jppf
when i tried to jppf on port 5000 and in can't. i can't telnet to 127.0.0.1 on port 5000

**Comment by rethab** [comment]
hi, i'm afraid to tell you that you're on your own here.. there were other tools I used at the time (which are not public) so it may well be that getting this to run relies on other things as well.. but honestly, I don't remember.

**Comment by hamidasgarian** [comment]
thank you for honestly
